import type { InsertGurpsTraitCatalogEntry } from "../drizzle/schema";

type SeedInput = [string, string, "advantage" | "disadvantage", number, string, string, string, string, boolean, boolean, string, string];
const row = ([name, originalName, kind, cost, costLabel, category, nature, availability, variableCost, requiresSelfControl, summary, reference]: SeedInput): InsertGurpsTraitCatalogEntry => ({
  id: `${kind === "advantage" ? "adv" : "dis"}-${originalName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
  name, originalName, kind, cost, costLabel, category, nature, availability, variableCost, requiresSelfControl, summary, reference,
});

// Custos variáveis usam 0 como sugestão inicial: o valor continua livremente editável na ficha.
export const getGurpsTraitCatalogSeed = (): InsertGurpsTraitCatalogEntry[] => {
  const entries: SeedInput[] = [
  ["Direção Absoluta", "Absolute Direction", "advantage", 5, "5", "Sentidos", "Mental", "Mundano", false, false, "Você se orienta com precisão e sabe onde fica o norte.", "Basic Set p. 34"],
  ["Tempo Absoluto", "Absolute Timing", "advantage", 2, "2", "Mental", "Mental", "Mundano", false, false, "Você estima intervalos de tempo com precisão incomum.", "Basic Set p. 35"],
  ["Senso Aguçado", "Acute Senses", "advantage", 2, "2/nível", "Sentidos", "Físico", "Mundano", false, false, "Melhora um sentido escolhido; informe o sentido e o nível nas notas.", "Basic Set p. 35"],
  ["Aliados", "Allies", "advantage", 0, "Variável", "Social", "Social", "Mundano", true, false, "Conta com um aliado definido pela campanha; ajuste o custo conforme poder e frequência.", "Basic Set p. 36"],
  ["Identidade Alternativa", "Alternate Identity", "advantage", 5, "5 ou 15", "Social", "Social", "Mundano", true, false, "Você possui uma identidade legal alternativa com os recursos correspondentes.", "Basic Set p. 39"],
  ["Ambidestria", "Ambidexterity", "advantage", 5, "5", "Físico", "Físico", "Mundano", false, false, "Reduz as penalidades por usar a mão inábil.", "Basic Set p. 39"],
  ["Empatia com Animais", "Animal Empathy", "advantage", 5, "5", "Mental", "Mental", "Mundano", false, false, "Facilita entender, acalmar e lidar com animais.", "Basic Set p. 40"],
  ["Aparência", "Appearance", "advantage", 0, "Variável", "Aparência", "Físico", "Mundano", true, false, "Define uma aparência atraente ou marcante; ajuste o custo pela opção escolhida.", "Basic Set p. 21"],
  ["Reflexos em Combate", "Combat Reflexes", "advantage", 15, "15", "Combate", "Mental", "Mundano", false, false, "Você reage melhor ao perigo e recebe benefícios nas defesas ativas.", "Basic Set p. 43"],
  ["Senso Comum", "Common Sense", "advantage", 10, "10", "Mental", "Mental", "Mundano", false, false, "O mestre pode alertar quando uma ideia comum parecer perigosa ou imprudente.", "Basic Set p. 43"],
  ["Adaptabilidade Cultural", "Cultural Adaptability", "advantage", 10, "10", "Social", "Mental", "Mundano", false, false, "Você evita penalidades por familiaridade cultural e aprende costumes depressa.", "Basic Set p. 46"],
  ["Resistência a Dano", "Damage Resistance", "advantage", 5, "5/nível", "Proteção", "Físico", "Exótico", false, false, "Concede DR natural; registre a origem, nível e limitações nas notas.", "Basic Set p. 46"],
  ["Senso de Perigo", "Danger Sense", "advantage", 15, "15", "Mental", "Mental", "Mundano", false, false, "Você recebe um aviso instintivo quando há risco iminente.", "Basic Set p. 47"],
  ["Audácia", "Daredevil", "advantage", 15, "15", "Mental", "Mental", "Mundano", false, false, "Favorece tentativas arriscadas e a resistência ao medo em situações perigosas.", "Basic Set p. 47"],
  ["Visão no Escuro", "Dark Vision", "advantage", 25, "25", "Sentidos", "Físico", "Exótico", false, false, "Você enxerga mesmo na escuridão total.", "Basic Set p. 47"],
  ["Memória Eidética", "Eidetic Memory", "advantage", 5, "5 ou 10", "Mental", "Mental", "Mundano", true, false, "Você recorda informações com excepcional precisão.", "Basic Set p. 51"],
  ["Empatia", "Empathy", "advantage", 15, "15", "Mental", "Mental", "Mundano", false, false, "Você percebe emoções e intenções alheias com mais facilidade.", "Basic Set p. 51"],
  ["Defesas Aprimoradas", "Enhanced Defenses", "advantage", 0, "Variável", "Combate", "Mental", "Mundano", true, false, "Melhora uma defesa ativa específica; anote a defesa e o custo escolhido.", "Basic Set p. 51"],
  ["Ataque Extra", "Extra Attack", "advantage", 25, "25/ataque", "Combate", "Físico", "Mundano", false, false, "Permite executar um ataque adicional por turno.", "Basic Set p. 53"],
  ["Sorte", "Luck", "advantage", 15, "Variável", "Mental", "Mental", "Mundano", true, false, "Permite repetir uma jogada em intervalos definidos pela versão de Sorte escolhida.", "Basic Set p. 66"],
  ["Magia", "Magery", "advantage", 15, "5 + 10/nível", "Mágico", "Mental", "Sobrenatural", true, false, "Concede aptidão mágica; informe o nível e os requisitos da campanha.", "Basic Set p. 66"],
  ["Noite Visível", "Night Vision", "advantage", 1, "1/nível", "Sentidos", "Físico", "Mundano", false, false, "Reduz penalidades para enxergar com pouca luz.", "Basic Set p. 71"],
  ["Equilíbrio Perfeito", "Perfect Balance", "advantage", 15, "15", "Físico", "Físico", "Mundano", false, false, "Você se equilibra excepcionalmente bem e recebe benefícios em testes relacionados.", "Basic Set p. 74"],
  ["Visão Periférica", "Peripheral Vision", "advantage", 15, "15", "Sentidos", "Físico", "Mundano", false, false, "Amplia seu campo de visão lateral.", "Basic Set p. 74"],
  ["Patrono", "Patrons", "advantage", 0, "Variável", "Social", "Social", "Mundano", true, false, "Você conta com o apoio de uma pessoa ou organização poderosa.", "Basic Set p. 72"],
  ["Propósito Maior", "Higher Purpose", "advantage", 5, "5", "Mental", "Mental", "Sobrenatural", false, false, "Você recebe bônus em uma missão específica definida pela campanha.", "Basic Set p. 59"],
  ["Boa Forma", "Fit", "advantage", 5, "5", "Físico", "Físico", "Mundano", false, false, "Você resiste melhor a fadiga, doença e esforço físico.", "Basic Set p. 55"],
  ["Muito em Forma", "Very Fit", "advantage", 15, "15", "Físico", "Físico", "Mundano", false, false, "Versão superior de Boa Forma para vigor excepcional.", "Basic Set p. 55"],
  ["Limiar Alto de Dor", "High Pain Threshold", "advantage", 10, "10", "Físico", "Físico", "Mundano", false, false, "Você suporta dor e choque físico melhor que o normal.", "Basic Set p. 59"],
  ["Intuição", "Intuition", "advantage", 15, "15", "Mental", "Mental", "Mundano", false, false, "Você pode pedir ao mestre uma impressão sobre uma decisão importante.", "Basic Set p. 63"],
  ["Voz", "Voice", "advantage", 10, "10", "Social", "Físico", "Mundano", false, false, "Sua voz é especialmente agradável ou persuasiva.", "Basic Set p. 97"],
  ["Riqueza", "Wealth", "advantage", 0, "Variável", "Social", "Social", "Mundano", true, false, "Ajusta recursos iniciais e renda conforme o nível econômico escolhido.", "Basic Set p. 25"],
  ["Sem Sorte", "Unluckiness", "disadvantage", -10, "-10", "Mental", "Mental", "Mundano", false, false, "O mestre pode transformar um resultado favorável em um contratempo ocasional.", "Basic Set p. 160"],
  ["Distraído", "Absent-Mindedness", "disadvantage", -15, "-15", "Mental", "Mental", "Mundano", false, false, "Você se distrai com facilidade e pode esquecer detalhes simples.", "Basic Set p. 122"],
  ["Vício", "Addiction", "disadvantage", 0, "Variável", "Mental", "Mental", "Mundano", true, false, "Dependência química ou comportamental; defina substância, legalidade e gravidade.", "Basic Set p. 122"],
  ["Alcoolismo", "Alcoholism", "disadvantage", -15, "-15 ou -20", "Mental", "Físico", "Mundano", true, false, "Você sofre dependência de álcool e seus efeitos sociais ou físicos.", "Basic Set p. 122"],
  ["Amnésia", "Amnesia", "disadvantage", -10, "-10 ou -25", "Mental", "Mental", "Mundano", true, false, "Você perdeu lembranças importantes; a extensão é definida com o mestre.", "Basic Set p. 123"],
  ["Costas Ruins", "Bad Back", "disadvantage", -15, "-15 ou -25", "Físico", "Físico", "Mundano", true, false, "Você sofre limitações e dor ao carregar peso ou realizar esforço.", "Basic Set p. 123"],
  ["Mau Gênio", "Bad Temper", "disadvantage", -10, "-10*", "Mental", "Mental", "Mundano", false, true, "Você deve testar autocontrole para evitar explosões de raiva.", "Basic Set p. 124"],
  ["Sanguinário", "Bloodlust", "disadvantage", -10, "-10*", "Mental", "Mental", "Mundano", false, true, "Você tende a levar confrontos até consequências violentas.", "Basic Set p. 125"],
  ["Covardia", "Cowardice", "disadvantage", -10, "-10*", "Mental", "Mental", "Mundano", false, true, "Você deve resistir ao impulso de fugir diante do perigo.", "Basic Set p. 129"],
  ["Curioso", "Curious", "disadvantage", -5, "-5*", "Mental", "Mental", "Mundano", false, true, "Você tem dificuldade em ignorar mistérios e novidades.", "Basic Set p. 129"],
  ["Surdez", "Deafness", "disadvantage", -20, "-20", "Físico", "Físico", "Mundano", false, false, "Você não ouve e enfrenta as limitações correspondentes.", "Basic Set p. 129"],
  ["Dívida", "Debt", "disadvantage", -1, "-1/nível", "Social", "Social", "Mundano", false, false, "Você deve parte de sua renda ou recursos a credores.", "Basic Set p. 26"],
  ["Dependentes", "Dependents", "disadvantage", 0, "Variável", "Social", "Social", "Mundano", true, false, "Pessoas sob sua responsabilidade podem exigir proteção e atenção.", "Basic Set p. 131"],
  ["Dever", "Duty", "disadvantage", 0, "Variável", "Social", "Social", "Mundano", true, false, "Você deve obedecer ou atender uma organização, pessoa ou causa.", "Basic Set p. 133"],
  ["Inimigos", "Enemies", "disadvantage", 0, "Variável", "Social", "Social", "Mundano", true, false, "Um inimigo ou grupo hostil surge conforme poder e frequência definidos.", "Basic Set p. 135"],
  ["Fanatismo", "Fanaticism", "disadvantage", -15, "-15", "Mental", "Mental", "Mundano", false, false, "Você defende uma crença ou causa acima de sua própria segurança.", "Basic Set p. 136"],
  ["Ganância", "Greed", "disadvantage", -15, "-15*", "Mental", "Mental", "Mundano", false, true, "Você deve resistir à tentação de lucro material relevante.", "Basic Set p. 137"],
  ["Honestidade", "Honesty", "disadvantage", -10, "-10*", "Mental", "Mental", "Mundano", false, true, "Você procura obedecer à lei e pode ter dificuldade com crimes.", "Basic Set p. 138"],
  ["Impulsividade", "Impulsiveness", "disadvantage", -10, "-10*", "Mental", "Mental", "Mundano", false, true, "Você tende a agir antes de planejar ou considerar consequências.", "Basic Set p. 139"],
  ["Intolerância", "Intolerance", "disadvantage", 0, "Variável", "Mental", "Mental", "Mundano", true, false, "Você reage mal a um grupo, ideia ou costume; registre o alvo da intolerância.", "Basic Set p. 140"],
  ["Ciúme", "Jealousy", "disadvantage", -10, "-10", "Mental", "Mental", "Mundano", false, false, "Você reage mal quando alguém recebe atenção ou afeto em seu lugar.", "Basic Set p. 140"],
  ["Preguiça", "Laziness", "disadvantage", -10, "-10", "Mental", "Mental", "Mundano", false, false, "Você evita trabalho e esforço quando existe uma alternativa.", "Basic Set p. 142"],
  ["Limiar Baixo de Dor", "Low Pain Threshold", "disadvantage", -10, "-10", "Físico", "Físico", "Mundano", false, false, "Você sofre penalidades maiores quando sente dor ou choque físico.", "Basic Set p. 142"],
  ["Paciência Curta", "Short Attention Span", "disadvantage", -10, "-10*", "Mental", "Mental", "Mundano", false, true, "Você se distrai de tarefas longas e perde foco rapidamente.", "Basic Set p. 153"],
  ["Código de Honra", "Code of Honor", "disadvantage", -10, "-5 a -15", "Mental", "Mental", "Mundano", true, false, "Você segue um conjunto de princípios que limita suas ações.", "Basic Set p. 127"],
  ["Fobia", "Phobias", "disadvantage", -5, "Variável*", "Mental", "Mental", "Mundano", true, true, "Você teme um objeto ou situação; defina o gatilho e a gravidade.", "Basic Set p. 148"],
  ["Voto", "Vow", "disadvantage", -5, "-1 ou -5 a -15", "Mental", "Mental", "Mundano", true, false, "Você assumiu uma promessa restritiva; descreva sua formulação nas notas.", "Basic Set p. 160"],
  ["Peculiaridade", "Quirk", "disadvantage", -1, "-1", "Mental", "Mental", "Mundano", false, false, "Uma característica menor de personalidade ou hábito marcante.", "Basic Set p. 162"],
  ];
  return entries.map(row);
};
